name: Update WakaTime Stats

on:
  schedule:
    - cron: '0 0 * * *' # Every day at midnight
  workflow_dispatch: # Allow manual runs

jobs:
  update-readme:
    name: Update wakatime stats in README
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: WakaTime Readme Stats
        uses: anmol098/waka-readme-stats@master
        with:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_LANGUAGE: true
          SHOW_OS: true
          SHOW_PROJECTS: true
          SHOW_EDITORS: true
          SHOW_LINES_OF_CODE: true
          SHOW_COMMIT: false
          SHOW_DAYS_OF_WEEK: false
          LOCALE: "en"
          COMPACT: true
          SHOW_TIME: true
          SHOW_TOTAL_CODE_TIME: true
          SHOW_LANGUAGE_PER_REPO: false
